/**
 * Simple I18n Manager
 * Supports: zh-TW, en, ja, ko, th, vi, id, ms, fr, de, es
 */
const Lang = {
    current: 'zh-TW', // Default
    translations: {
        'zh-TW': {
            meta: {
                description: 'Pixel Sprite Studio 是一個強大的線上像素精靈製作工具。輕鬆去背、組裝角色、調整動畫，並輸出為 PNG 或 GIF 動圖。適合遊戲開發者與像素藝術愛好者。',
                keywords: '像素製作, Sprite Maker, sprite sheet, 去背工具, 像素藝術, Pixel Art, 遊戲素材, GIF 產生器'
            },
            'app.title': 'Pixel Sprite Studio - 像素精靈製作與編輯工具',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': '設置',
            'ui.library': '素材庫',
            'ui.add': '新增',
            'ui.tab.character': '角色',
            'ui.tab.accessory': '配飾',
            'ui.preview.title': '實時預覽',
            'ui.preview.desc': '最終輸出效果',
            'ui.editor.title': '編輯器',
            'ui.editor.desc': '調整配飾位置與大小',
            'ui.controls.title': '配飾調整',
            'ui.msg.no_selection': '請選中配飾以編輯',
            'ctrl.bobbing': '跳動幅度 (Bobbing)',
            'ctrl.scale': '縮放 (Scale)',
            'ctrl.rotation': '旋轉 (Rotation)',
            'ctrl.zoom': '角色縮放 (Zoom) [預覽]',
            'ctrl.bgcolor': '背景顏色 / 透明',
            'ctrl.transparent': '透明背景',
            'ctrl.bg_desc': '影響預覽與輸出；勾選透明時忽略顏色。',
            'btn.save_png': '輸出 PNG',
            'btn.save_gif': '輸出 GIF',
            'tutorial.title': '快速上手指南',
            'tutorial.subtitle': '三步驟輕鬆完成專屬像素精靈！',
            'step.1.title': '1. 素材生成 (Upload)',
            'step.1.desc': '開啟「素材生成工廠」，上傳您的圖片。調整去背容許度，讓 Nano Banana 幫您自動去背並提取物件！',
            'step.2.title': '2. 角色組裝 (Equip)',
            'step.2.desc': '在左側庫存點選角色與配飾。點擊配件即可裝備，享受自由搭配的樂趣！',
            'step.3.title': '3. 細節調整 (Edit)',
            'step.3.desc': '使用下方編輯器微調位置、旋轉與動畫跳動幅度。完成後點擊下載，將您的作品帶回家！',
            'factory.title': '素材生成工廠',
            'factory.tab.char': '角色生成',
            'factory.tab.acc': '配飾生成',
            'factory.source': '來源',
            'factory.preview.placeholder': '請上傳圖片',
            'factory.tolerance': '去背容許度 (Tolerance):',
            'factory.bg.status': '背景色',
            'factory.bg.auto': '自動',
            'factory.bg.manual': '手動',
            'factory.bg.picking': '吸取中',
            'factory.bg.pick_btn': '手動吸取背景色',
            'factory.bg.cancel_prod': '取消吸取',
            'factory.bg.reset_btn': '回到自動',
            'factory.bg.hint.auto': '自動：取四角多數顏色。手動：按「吸取背景色」後點圖（5×5 平均）。',
            'factory.bg.hint.picking': '吸取中：點擊上方圖片的背景色（5×5 平均），或按 Esc / 點「取消吸取」。',
            'factory.bg.hint.manual': '手動：已覆寫背景色。可再次吸取或按「回到自動」恢復自動偵測。',
            'factory.frames': '目標格數 (Frames):',
            'factory.select_method': '格擷取方式',
            'factory.select_desc': '依像素數量：較能過濾雜點；原圖順序：保留排列但可能保留雜點；自定義排列：拖拉排序 / 刪除格子。',
            'factory.method.size': '依像素數量（去雜質）',
            'factory.method.order': '原圖順序（左至右，上至下）',
            'factory.method.custom': '自定義排列',
            'factory.custom_hint': '拖拉格子可重新排序，叉叉可移除。重新上傳或切換模式會重置自定義排列。',
            'btn.add_to_library': '加入庫存',
            'msg.added': '已加入庫存',
            'msg.upload_first': '請先上傳圖片',
            'msg.saved_png': '已下載組合圖片',
            'msg.no_char': '請先選擇角色',
            'msg.no_obj': '未偵測到物件'
        },
        'en': {
            meta: {
                description: 'Pixel Sprite Studio is a powerful online tool for creating pixel art sprites. Remove backgrounds, assemble characters, adjust animations, and export as PNG or GIF. Perfect for game devs and artists.',
                keywords: 'pixel art, sprite maker, sprite sheet, background remover, game assets, gif generator, pixel editor'
            },
            'app.title': 'Pixel Sprite Studio - Sprite Maker & Editor',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': 'Settings',
            'ui.library': 'Library',
            'ui.add': 'Add',
            'ui.tab.character': 'Character',
            'ui.tab.accessory': 'Accessory',
            'ui.preview.title': 'Live Preview',
            'ui.preview.desc': 'Final Output',
            'ui.editor.title': 'Editor',
            'ui.editor.desc': 'Adjust Position & Size',
            'ui.controls.title': 'Adjustments',
            'ui.msg.no_selection': 'Select an accessory to edit',
            'ctrl.bobbing': 'Bobbing',
            'ctrl.scale': 'Scale',
            'ctrl.rotation': 'Rotation',
            'ctrl.zoom': 'View Zoom [Preview]',
            'ctrl.bgcolor': 'Background Color / Transparent',
            'ctrl.transparent': 'Transparent',
            'ctrl.bg_desc': 'Affects preview & output; overrides color when checked.',
            'btn.save_png': 'Export PNG',
            'btn.save_gif': 'Export GIF',
            'tutorial.title': 'Quick Start Guide',
            'tutorial.subtitle': 'Create your custom pixel sprite in 3 steps!',
            'step.1.title': '1. Generate (Upload)',
            'step.1.desc': 'Open "Sprite Factory", upload your image. Adjust tolerance to auto-remove background and extract sprites!',
            'step.2.title': '2. Assemble (Equip)',
            'step.2.desc': 'Select characters and accessories from the library. Click to equip and mix & match freely!',
            'step.3.title': '3. Edit (Adjust)',
            'step.3.desc': 'Use the editor to tweak position, rotation, and bobbing. Click export to take your sprite home!',
            'factory.title': 'Sprite Factory',
            'factory.tab.char': 'Character',
            'factory.tab.acc': 'Accessory',
            'factory.source': 'Source',
            'factory.preview.placeholder': 'Please upload an image',
            'factory.tolerance': 'Tolerance:',
            'factory.bg.status': 'BG Color',
            'factory.bg.auto': 'Auto',
            'factory.bg.manual': 'Manual',
            'factory.bg.picking': 'Picking',
            'factory.bg.pick_btn': 'Pick Color',
            'factory.bg.cancel_prod': 'Cancel',
            'factory.bg.reset_btn': 'Reset Auto',
            'factory.bg.hint.auto': 'Auto: Majority color from corners. Manual: Click "Pick Color" then click image.',
            'factory.bg.hint.picking': 'Picking: Click background on image (5x5 avg), or Esc / Cancel.',
            'factory.bg.hint.manual': 'Manual: Overridden. Pick again or Reset to Auto.',
            'factory.frames': 'Target Frames:',
            'factory.select_method': 'Extraction Method',
            'factory.select_desc': 'Size: Filters noise; Order: Preserves layout; Custom: Drag & Drop.',
            'factory.method.size': 'By Pixel Size (Clean)',
            'factory.method.order': 'Original Order (L-R, T-B)',
            'factory.method.custom': 'Custom Order',
            'factory.custom_hint': 'Drag to reorder, click X to remove. Reset on re-upload or mode switch.',
            'btn.add_to_library': 'Add to Library',
            'msg.added': 'Added to Library',
            'msg.upload_first': 'Please upload an image first',
            'msg.saved_png': 'Composition saved',
            'msg.no_char': 'Please select a character first',
            'msg.no_obj': 'No objects detected'
        },
        'ja': {
            meta: {
                description: 'Pixel Sprite Studioは、強力なオンラインドット絵スプライト作成ツールです。背景削除、キャラクター組み立て、アニメーション調整、PNGやGIFへの書き出しが簡単に行えます。',
                keywords: 'ドット絵, スプライト作成, スプライトシート, 背景透過, ゲーム素材, GIF作成, ピクセルアート'
            },
            'app.title': 'Pixel Sprite Studio - ドット絵エディタ & 生成',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': '設定',
            'ui.library': 'ライブラリ',
            'ui.add': '追加',
            'ui.tab.character': 'キャラクター',
            'ui.tab.accessory': 'アクセサリー',
            'ui.preview.title': 'プレビュー',
            'ui.preview.desc': '最終出力',
            'ui.editor.title': 'エディタ',
            'ui.editor.desc': '位置とサイズを調整',
            'ui.controls.title': 'プロパティ',
            'ui.msg.no_selection': 'アクセサリーを選択して編集',
            'ctrl.bobbing': '揺れ幅 (Bobbing)',
            'ctrl.scale': 'サイズ (Scale)',
            'ctrl.rotation': '回転 (Rotation)',
            'ctrl.zoom': '表示ズーム (Zoom)',
            'ctrl.bgcolor': '背景色 / 透明',
            'ctrl.transparent': '透明背景',
            'ctrl.bg_desc': 'プレビューと出力に影響します。チェック時は色を無視します。',
            'btn.save_png': 'PNG出力',
            'btn.save_gif': 'GIF出力',
            'tutorial.title': 'クイックスタート',
            'tutorial.subtitle': '3ステップであなただけのドット絵を作成！',
            'step.1.title': '1. 生成 (Upload)',
            'step.1.desc': '「スプライト工場」で画像をアップロード。許容値を調整して背景を自動削除し、パーツを抽出！',
            'step.2.title': '2. 組み立て (Equip)',
            'step.2.desc': 'ライブラリからキャラとアクセを選択。クリックで装備して自由に組み合わせよう！',
            'step.3.title': '3. 調整 (Edit)',
            'step.3.desc': 'エディタで位置や揺れを微調整。完成したら書き出しボタンでダウンロード！',
            'factory.title': 'スプライト工場',
            'factory.tab.char': 'キャラ生成',
            'factory.tab.acc': 'アクセ生成',
            'factory.source': 'ソース',
            'factory.preview.placeholder': '画像をアップロードしてください',
            'factory.tolerance': '許容値 (Tolerance):',
            'factory.bg.status': '背景色',
            'factory.bg.auto': '自動',
            'factory.bg.manual': '手動',
            'factory.bg.picking': 'スポイト中',
            'factory.bg.pick_btn': 'スポイトツール',
            'factory.bg.cancel_prod': 'キャンセル',
            'factory.bg.reset_btn': '自動に戻す',
            'factory.bg.hint.auto': '自動：四隅の色から判定。手動：「スポイト」で画像をクリック。',
            'factory.bg.hint.picking': 'スポイト中：背景色をクリック（5x5平均）、Escでキャンセル。',
            'factory.bg.hint.manual': '手動：設定済み。再指定するか「自動に戻す」を押してください。',
            'factory.frames': 'フレーム数:',
            'factory.select_method': '抽出モード',
            'factory.select_desc': 'サイズ順：ノイズ除去； 元順：レイアウト維持； カスタム：ドラッグ並べ替え。',
            'factory.method.size': 'サイズ順 (クリーン)',
            'factory.method.order': '元の順序 (左→右)',
            'factory.method.custom': 'カスタム並べ替え',
            'factory.custom_hint': 'ドラッグで並べ替え、×で削除。再アップロードでリセット。',
            'btn.add_to_library': 'ライブラリに追加',
            'msg.added': 'ライブラリに追加しました',
            'msg.upload_first': '先に画像をアップロードしてください',
            'msg.saved_png': '画像を保存しました',
            'msg.no_char': '先にキャラクターを選択してください',
            'msg.no_obj': 'オブジェクトが見つかりません'
        },
        'ko': {
            meta: {
                description: 'Pixel Sprite Studio는 강력한 온라인 픽셀 아트 스프라이트 제작 도구입니다. 배경 제거, 캐릭터 조립, 애니메이션 조정을 손쉽게 하고 PNG 또는 GIF로 내보내세요.',
                keywords: '픽셀 아트, 스프라이트 메이커, 도트 찍기, 배경 제거, 게임 자산, GIF 생성기'
            },
            'app.title': 'Pixel Sprite Studio - 픽셀 스프라이트 제작 도구',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': '설정',
            'ui.library': '라이브러리',
            'ui.add': '추가',
            'ui.tab.character': '캐릭터',
            'ui.tab.accessory': '액세서리',
            'ui.preview.title': '미리보기',
            'ui.preview.desc': '최종 결과물',
            'ui.editor.title': '에디터',
            'ui.editor.desc': '위치 및 크기 조정',
            'ui.controls.title': '속성',
            'ui.msg.no_selection': '편집할 액세서리를 선택하세요',
            'ctrl.bobbing': '움직임 (Bobbing)',
            'ctrl.scale': '크기 (Scale)',
            'ctrl.rotation': '회전 (Rotation)',
            'ctrl.zoom': '화면 확대 (Zoom)',
            'ctrl.bgcolor': '배경색 / 투명',
            'ctrl.transparent': '투명 배경',
            'ctrl.bg_desc': '미리보기 및 출력에 적용됩니다. 체크 시 색상 무시.',
            'btn.save_png': 'PNG 내보내기',
            'btn.save_gif': 'GIF 내보내기',
            'tutorial.title': '시작 가이드',
            'tutorial.subtitle': '3단계로 나만의 픽셀 캐릭터 완성!',
            'step.1.title': '1. 생성 (Upload)',
            'step.1.desc': '「스프라이트 공장」에서 이미지 업로드. 허용치를 조절해 배경을 자동 제거하고 파츠를 추출하세요!',
            'step.2.title': '2. 조립 (Equip)',
            'step.2.desc': '라이브러리에서 캐릭터와 장식을 선택. 클릭하여 장착하고 자유롭게 꾸며보세요!',
            'step.3.title': '3. 조정 (Edit)',
            'step.3.desc': '에디터로 위치와 애니메이션을 미세 조정. 완료되면 내보내기 버튼으로 다운로드!',
            'factory.title': '스프라이트 공장',
            'factory.tab.char': '캐릭터 생성',
            'factory.tab.acc': '장식 생성',
            'factory.source': '원본',
            'factory.preview.placeholder': '이미지를 업로드하세요',
            'factory.tolerance': '허용치 (Tolerance):',
            'factory.bg.status': '배경색',
            'factory.bg.auto': '자동',
            'factory.bg.manual': '수동',
            'factory.bg.picking': '스포이드',
            'factory.bg.pick_btn': '배경색 추출',
            'factory.bg.cancel_prod': '취소',
            'factory.bg.reset_btn': '자동 복귀',
            'factory.bg.hint.auto': '자동: 모서리 색상 기준. 수동: 「추출」 클릭 후 이미지 클릭.',
            'factory.bg.hint.picking': '추출 중: 배경 클릭 (5x5 평균), Esc로 취소.',
            'factory.bg.hint.manual': '수동: 설정됨. 다시 추출하거나 자동 복귀.',
            'factory.frames': '프레임 수:',
            'factory.select_method': '추출 모드',
            'factory.select_desc': '크기순: 노이즈 제거; 원래순서: 레이아웃 유지; 사용자지정: 드래그 정렬.',
            'factory.method.size': '크기순 (깔끔함)',
            'factory.method.order': '원래 순서 (좌-우)',
            'factory.method.custom': '사용자 지정 정렬',
            'factory.custom_hint': '드래그하여 재정렬, X로 삭제. 재업로드 시 초기화.',
            'btn.add_to_library': '라이브러리에 추가',
            'msg.added': '추가되었습니다',
            'msg.upload_first': '먼저 이미지를 업로드하세요',
            'msg.saved_png': '이미지가 저장되었습니다',
            'msg.no_char': '먼저 캐릭터를 선택하세요',
            'msg.no_obj': '객체를 찾을 수 없습니다'
        },
        'th': {
            meta: {
                description: 'Pixel Sprite Studio เป็นเครื่องมือออนไลน์ที่มีประสิทธิภาพสำหรับการสร้างพิกเซลอาร์ตสไปรต์ ลบพื้นหลัง ประกอบตัวละคร ปรับแต่งแอนิเมชั่น และส่งออกเป็น PNG หรือ GIF',
                keywords: 'พิกเซลอาร์ต, สร้างสไปรต์, ลบพื้นหลัง, ทรัพย์สินเกม, GIF, พิกเซล'
            },
            'app.title': 'Pixel Sprite Studio - สร้างและแก้ไขสไปรต์พิกเซล',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': 'ตั้งค่า',
            'ui.library': 'ไลบรารี',
            'ui.add': 'เพิ่ม',
            'ui.tab.character': 'ตัวละคร',
            'ui.tab.accessory': 'เครื่องประดับ',
            'ui.preview.title': 'พรีวิว',
            'ui.preview.desc': 'ผลลัพธ์สุดท้าย',
            'ui.editor.title': 'แก้ไข',
            'ui.editor.desc': 'ปรับตำแหน่งและขนาด',
            'ui.controls.title': 'ปรับแต่ง',
            'ui.msg.no_selection': 'เลือกเครื่องประดับเพื่อแก้ไข',
            'ctrl.bobbing': 'การเด้ง (Bobbing)',
            'ctrl.scale': 'ขนาด (Scale)',
            'ctrl.rotation': 'การหมุน (Rotation)',
            'ctrl.zoom': 'ซูมมุมมอง (Zoom)',
            'ctrl.bgcolor': 'สีพื้นหลัง / โปร่งใส',
            'ctrl.transparent': 'พื้นหลังโปร่งใส',
            'ctrl.bg_desc': 'มีผลกับพรีวิวและการส่งออก; หากติ๊กจะเพิกเฉยต่อสี',
            'btn.save_png': 'ส่งออก PNG',
            'btn.save_gif': 'ส่งออก GIF',
            'tutorial.title': 'คู่มือเริ่มต้น',
            'tutorial.subtitle': 'สร้างสไปรต์ของคุณใน 3 ขั้นตอน!',
            'step.1.title': '1. สร้าง (Upload)',
            'step.1.desc': 'เปิด "โรงงานสไปรต์" อัปโหลดภาพ ปรับค่าความคลาดเคลื่อนเพื่อลบพื้นหลังอัตโนมัติและแยกชิ้นส่วน!',
            'step.2.title': '2. ประกอบ (Equip)',
            'step.2.desc': 'เลือกตัวละครและเครื่องประดับจากไลบรารี คลิกเพื่อสวมใส่และผสมผสานได้ตามใจ!',
            'step.3.title': '3. ปรับแต่ง (Edit)',
            'step.3.desc': 'ใช้ตัวแก้ไขเพื่อปรับตำแหน่งและการเคลื่อนไหว เมื่อเสร็จแล้วคลิกส่งออกเพื่อบันทึกงานของคุณ!',
            'factory.title': 'โรงงานสไปรต์',
            'factory.tab.char': 'สร้างตัวละคร',
            'factory.tab.acc': 'สร้างของตกแต่ง',
            'factory.source': 'ต้นฉบับ',
            'factory.preview.placeholder': 'กรุณาอัปโหลดภาพ',
            'factory.tolerance': 'ความคลาดเคลื่อน:',
            'factory.bg.status': 'สีพื้นหลัง',
            'factory.bg.auto': 'อัตโนมัติ',
            'factory.bg.manual': 'กำหนดเอง',
            'factory.bg.picking': 'กำลังดูดสี',
            'factory.bg.pick_btn': 'ดูดสีพื้นหลัง',
            'factory.bg.cancel_prod': 'ยกเลิก',
            'factory.bg.reset_btn': 'รีเซ็ตเป็นอัตโนมัติ',
            'factory.bg.hint.auto': 'อัตโนมัติ: สีส่วนใหญ่จากมุมภาพ',
            'factory.bg.hint.picking': 'คลิกที่สีพื้นหลังในภาพ (เฉลี่ย 5x5) หรือกด Esc',
            'factory.bg.hint.manual': 'กำหนดเอง: ถูกเขียนทับแล้ว',
            'factory.frames': 'จำนวนเฟรม:',
            'factory.select_method': 'วิธีการแยก',
            'factory.select_desc': 'ขนาด: กรองจุดรบกวน; ลำดับ: คงเลย์เอาต์; กำหนดเอง: ลากวาง',
            'factory.method.size': 'ตามขนาด (สะอาด)',
            'factory.method.order': 'ลำดับเดิม',
            'factory.method.custom': 'กำหนดลำดับเอง',
            'factory.custom_hint': 'ลากเพื่อเรียงใหม่, X เพื่อลบ',
            'btn.add_to_library': 'เพิ่มลงไลบรารี',
            'msg.added': 'เพิ่มแล้ว',
            'msg.upload_first': 'กรุณาอัปโหลดภาพก่อน',
            'msg.saved_png': 'บันทึกภาพแล้ว',
            'msg.no_char': 'กรุณาเลือกตัวละครก่อน',
            'msg.no_obj': 'ไม่พบวัตถุ'
        },
        'vi': {
            meta: {
                description: 'Pixel Sprite Studio là công cụ trực tuyến mạnh mẽ để tạo sprite pixel art. Xóa nền, lắp ráp nhân vật, điều chỉnh hoạt ảnh và xuất ra PNG hoặc GIF.',
                keywords: 'pixel art, tạo sprite, xóa phông, tài nguyên game, tạo gif'
            },
            'app.title': 'Pixel Sprite Studio - Trình tạo & Chỉnh sửa Sprite',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': 'Cài đặt',
            'ui.library': 'Thư viện',
            'ui.add': 'Thêm',
            'ui.tab.character': 'Nhân vật',
            'ui.tab.accessory': 'Phụ kiện',
            'ui.preview.title': 'Xem trước',
            'ui.preview.desc': 'Kết quả xuất',
            'ui.editor.title': 'Trình chỉnh sửa',
            'ui.editor.desc': 'Chỉnh vị trí & kích thước',
            'ui.controls.title': 'Điều chỉnh',
            'ui.msg.no_selection': 'Chọn phụ kiện để sửa',
            'ctrl.bobbing': 'Độ nhún (Bobbing)',
            'ctrl.scale': 'Tỷ lệ (Scale)',
            'ctrl.rotation': 'Xoay (Rotation)',
            'ctrl.zoom': 'Thu phóng (Zoom)',
            'ctrl.bgcolor': 'Màu nền / Trong suốt',
            'ctrl.transparent': 'Nền trong suốt',
            'ctrl.bg_desc': 'Ảnh hưởng đến xem trước và xuất file.',
            'btn.save_png': 'Xuất PNG',
            'btn.save_gif': 'Xuất GIF',
            'tutorial.title': 'Hướng dẫn nhanh',
            'tutorial.subtitle': 'Tạo sprite của bạn trong 3 bước!',
            'step.1.title': '1. Tạo (Upload)',
            'step.1.desc': 'Mở "Xưởng Sprite", tải ảnh lên. Chỉnh độ sai số để tự động xóa nền và tách vật thể!',
            'step.2.title': '2. Lắp ráp (Equip)',
            'step.2.desc': 'Chọn nhân vật và phụ kiện từ thư viện. Nhấn để trang bị và phối đồ tự do!',
            'step.3.title': '3. Chỉnh sửa (Edit)',
            'step.3.desc': 'Dùng trình chỉnh sửa để tinh chỉnh. Nhấn nút xuất để tải về tác phẩm của bạn!',
            'factory.title': 'Xưởng Sprite',
            'factory.tab.char': 'Tạo NV',
            'factory.tab.acc': 'Tạo PK',
            'factory.source': 'Nguồn',
            'factory.preview.placeholder': 'Vui lòng tải ảnh',
            'factory.tolerance': 'Độ sai số:',
            'factory.bg.status': 'Màu nền',
            'factory.bg.auto': 'Tự động',
            'factory.bg.manual': 'Thủ công',
            'factory.bg.picking': 'Đang chọn',
            'factory.bg.pick_btn': 'Chọn màu nền',
            'factory.bg.cancel_prod': 'Hủy',
            'factory.bg.reset_btn': 'Về tự động',
            'factory.bg.hint.auto': 'Tự động: Lấy màu đa số từ góc.',
            'factory.bg.hint.picking': 'Click vào màu nền trên hình (TB 5x5) hoặc Esc.',
            'factory.bg.hint.manual': 'Thủ công: Đã ghi đè.',
            'factory.frames': 'Số khung hình:',
            'factory.select_method': 'Cách trích xuất',
            'factory.select_desc': 'Kích thước: Lọc nhiễu; Thứ tự: Giữ bố cục; Tùy chỉnh: Kéo thả.',
            'factory.method.size': 'Theo kích thước',
            'factory.method.order': 'Thứ tự gốc',
            'factory.method.custom': 'Tùy chỉnh thứ tự',
            'factory.custom_hint': 'Kéo để sắp xếp, X để xóa.',
            'btn.add_to_library': 'Thêm vào kho',
            'msg.added': 'Đã thêm vào kho',
            'msg.upload_first': 'Vui lòng tải ảnh trước',
            'msg.saved_png': 'Đã lưu ảnh',
            'msg.no_char': 'Chọn nhân vật trước',
            'msg.no_obj': 'Không tìm thấy vật thể'
        },
        'id': {
            meta: {
                description: 'Pixel Sprite Studio adalah alat online canggih untuk membuat sprite seni piksel. Hapus latar belakang, rakit karakter, sesuaikan animasi, dan ekspor sebagai PNG atau GIF.',
                keywords: 'seni piksel, pembuat sprite, lembar sprite, penghapus latar belakang, aset game'
            },
            'app.title': 'Pixel Sprite Studio - Pembuat & Editor Sprite',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': 'Pengaturan',
            'ui.library': 'Koleksi',
            'ui.add': 'Tambah',
            'ui.tab.character': 'Karakter',
            'ui.tab.accessory': 'Aksesori',
            'ui.preview.title': 'Pratinjau',
            'ui.preview.desc': 'Hasil Akhir',
            'ui.editor.title': 'Editor',
            'ui.editor.desc': 'Atur Posisi & Ukuran',
            'ui.controls.title': 'Penyesuaian',
            'ui.msg.no_selection': 'Pilih aksesori untuk diedit',
            'ctrl.bobbing': 'Bobbing (Naik-Turun)',
            'ctrl.scale': 'Skala',
            'ctrl.rotation': 'Rotasi',
            'ctrl.zoom': 'Zoom Tampilan',
            'ctrl.bgcolor': 'Warna Latar / Transparan',
            'ctrl.transparent': 'Latar Transparan',
            'ctrl.bg_desc': 'Mempengaruhi pratinjau & hasil; abaikan warna saat dicentang.',
            'btn.save_png': 'Ekspor PNG',
            'btn.save_gif': 'Ekspor GIF',
            'tutorial.title': 'Panduan Cepat',
            'tutorial.subtitle': 'Buat sprite kustom Anda dalam 3 langkah!',
            'step.1.title': '1. Buat (Upload)',
            'step.1.desc': 'Buka "Pabrik Sprite", unggah gambar. Atur toleransi untuk hapus background otomatis!',
            'step.2.title': '2. Rakit (Equip)',
            'step.2.desc': 'Pilih karakter dan aksesori dari koleksi. Klik untuk pakai dan kombinasikan sesuka hati!',
            'step.3.title': '3. Edit (Adjust)',
            'step.3.desc': 'Gunakan editor untuk atur posisi dan animasi. Klik ekspor untuk simpan karya Anda!',
            'factory.title': 'Pabrik Sprite',
            'factory.tab.char': 'Karakter',
            'factory.tab.acc': 'Aksesori',
            'factory.source': 'Sumber',
            'factory.preview.placeholder': 'Silakan unggah gambar',
            'factory.tolerance': 'Toleransi:',
            'factory.bg.status': 'Warna BG',
            'factory.bg.auto': 'Otomatis',
            'factory.bg.manual': 'Manual',
            'factory.bg.picking': 'Memilih',
            'factory.bg.pick_btn': 'Ambil Warna',
            'factory.bg.cancel_prod': 'Batal',
            'factory.bg.reset_btn': 'Reset Otomatis',
            'factory.bg.hint.auto': 'Otomatis: Warna mayoritas dari sudut.',
            'factory.bg.hint.picking': 'Klik warna latar pada gambar (rata-rata 5x5), atau Esc.',
            'factory.bg.hint.manual': 'Manual: Diganti. Ambil lagi atau Reset.',
            'factory.frames': 'Jumlah Frame:',
            'factory.select_method': 'Metode Ekstraksi',
            'factory.select_desc': 'Ukuran: Filter noise; Urutan: Jaga tata letak; Kustom: Seret & Lepas.',
            'factory.method.size': 'Berdasarkan Ukuran',
            'factory.method.order': 'Urutan Asli',
            'factory.method.custom': 'Urutan Kustom',
            'factory.custom_hint': 'Seret untuk urutkan, klik X untuk hapus.',
            'btn.add_to_library': 'Tambah ke Koleksi',
            'msg.added': 'Ditambahkan ke Koleksi',
            'msg.upload_first': 'Unggah gambar dulu',
            'msg.saved_png': 'Tersimpan',
            'msg.no_char': 'Pilih karakter dulu',
            'msg.no_obj': 'Objek tidak ditemukan'
        },
        'ms': {
            meta: {
                description: 'Pixel Sprite Studio adalah alat dalam talian yang hebat untuk mencipta sprite seni piksel. Buang latar belakang, pasang watak, laraskan animasi, dan eksport sebagai PNG atau GIF.',
                keywords: 'seni piksel, pembuat sprite, helaian sprite, pembuang latar belakang, aset permainan'
            },
            'app.title': 'Pixel Sprite Studio - Pembuat & Editor Sprite',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': 'Tetapan',
            'ui.library': 'Pustaka',
            'ui.add': 'Tambah',
            'ui.tab.character': 'Watak',
            'ui.tab.accessory': 'Aksesori',
            'ui.preview.title': 'Pratonton',
            'ui.preview.desc': 'Hasil Akhir',
            'ui.editor.title': 'Editor',
            'ui.editor.desc': 'Laraskan Posisi & Saiz',
            'ui.controls.title': 'Pelarasan',
            'ui.msg.no_selection': 'Pilih aksesori untuk edit',
            'ctrl.bobbing': 'Deyutan (Bobbing)',
            'ctrl.scale': 'Skala',
            'ctrl.rotation': 'Putaran',
            'ctrl.zoom': 'Zum Paparan',
            'ctrl.bgcolor': 'Warna Latar / Lutsinar',
            'ctrl.transparent': 'Latar Lutsinar',
            'ctrl.bg_desc': 'Mempengaruhi pratonton & hasil.',
            'btn.save_png': 'Eksport PNG',
            'btn.save_gif': 'Eksport GIF',
            'tutorial.title': 'Panduan Pantas',
            'tutorial.subtitle': 'Cipta sprite anda dalam 3 langkah!',
            'step.1.title': '1. Cipta (Upload)',
            'step.1.desc': 'Buka "Kilang Sprite", muat naik imej. Laraskan toleransi untuk buang latar belakang secara auto!',
            'step.2.title': '2. Pasang (Equip)',
            'step.2.desc': 'Pilih watak dan aksesori. Klik untuk pakai dan padankan secara bebas!',
            'step.3.title': '3. Edit (Adjust)',
            'step.3.desc': 'Gunakan editor untuk ubah suai. Klik butang eksport untuk simpan karya anda!',
            'factory.title': 'Kilang Sprite',
            'factory.tab.char': 'Watak',
            'factory.tab.acc': 'Aksesori',
            'factory.source': 'Sumber',
            'factory.preview.placeholder': 'Sila muat naik imej',
            'factory.tolerance': 'Toleransi:',
            'factory.bg.status': 'Warna BG',
            'factory.bg.auto': 'Auto',
            'factory.bg.manual': 'Manual',
            'factory.bg.picking': 'Memilih',
            'factory.bg.pick_btn': 'Pilih Warna',
            'factory.bg.cancel_prod': 'Batal',
            'factory.bg.reset_btn': 'Reset Auto',
            'factory.bg.hint.auto': 'Auto: Warna majoriti dari sudut.',
            'factory.bg.hint.picking': 'Klik warna latar pada imej (purata 5x5), atau Esc.',
            'factory.bg.hint.manual': 'Manual: Diganti. Pilih semula atau Reset.',
            'factory.frames': 'Jumlah Bingkai:',
            'factory.select_method': 'Kaedah Ekstrak',
            'factory.select_desc': 'Saiz: Tapis hingar; Urutan: Kekalkan susun atur; Tersuai: Seret & Lepas.',
            'factory.method.size': 'Ikut Saiz',
            'factory.method.order': 'Urutan Asal',
            'factory.method.custom': 'Urutan Tersuai',
            'factory.custom_hint': 'Seret untuk susun semula, X untuk buang.',
            'btn.add_to_library': 'Tambah ke Pustaka',
            'msg.added': 'Ditambah ke Pustaka',
            'msg.upload_first': 'Sila muat naik imej dulu',
            'msg.saved_png': 'Disimpan',
            'msg.no_char': 'Pilih watak dulu',
            'msg.no_obj': 'Objek tidak dijumpai'
        },
        'fr': {
            meta: {
                description: 'Pixel Sprite Studio est un outil en ligne puissant pour créer des sprites en pixel art. Supprimez l\'arrière-plan, assemblez des personnages, ajustez les animations et exportez en PNG ou GIF.',
                keywords: 'pixel art, créateur de sprites, sprite sheet, détourage, assets de jeu, générateur de gif'
            },
            'app.title': 'Pixel Sprite Studio - Créateur de Sprites',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': 'Paramètres',
            'ui.library': 'Bibliothèque',
            'ui.add': 'Ajouter',
            'ui.tab.character': 'Perso',
            'ui.tab.accessory': 'Accessoire',
            'ui.preview.title': 'Aperçu',
            'ui.preview.desc': 'Résultat Final',
            'ui.editor.title': 'Éditeur',
            'ui.editor.desc': 'Position & Taille',
            'ui.controls.title': 'Réglages',
            'ui.msg.no_selection': 'Sélectionnez un accessoire',
            'ctrl.bobbing': 'Rebond (Bobbing)',
            'ctrl.scale': 'Échelle (Scale)',
            'ctrl.rotation': 'Rotation',
            'ctrl.zoom': 'Zoom Vue',
            'ctrl.bgcolor': 'Couleur de fond',
            'ctrl.transparent': 'Fond Transparent',
            'ctrl.bg_desc': 'Affecte l\'aperçu et l\'export.',
            'btn.save_png': 'Exporter PNG',
            'btn.save_gif': 'Exporter GIF',
            'tutorial.title': 'Guide Rapide',
            'tutorial.subtitle': 'Créez votre sprite en 3 étapes !',
            'step.1.title': '1. Générer (Upload)',
            'step.1.desc': 'Ouvrez "Usine à Sprites", chargez votre image. Réglez la tolérance pour détourer automatiquement !',
            'step.2.title': '2. Assembler (Equip)',
            'step.2.desc': 'Choisissez perso et accessoires. Cliquez pour équiper et mélanger librement !',
            'step.3.title': '3. Éditer (Edit)',
            'step.3.desc': 'Utilisez l\'éditeur pour ajuster. Cliquez sur exporter pour sauvegarder votre œuvre !',
            'factory.title': 'Usine à Sprites',
            'factory.tab.char': 'Personnage',
            'factory.tab.acc': 'Accessoire',
            'factory.source': 'Source',
            'factory.preview.placeholder': 'Veuillez charger une image',
            'factory.tolerance': 'Tolérance:',
            'factory.bg.status': 'Couleur Fond',
            'factory.bg.auto': 'Auto',
            'factory.bg.manual': 'Manuel',
            'factory.bg.picking': 'Pipette',
            'factory.bg.pick_btn': 'Pipette',
            'factory.bg.cancel_prod': 'Annuler',
            'factory.bg.reset_btn': 'Reset Auto',
            'factory.bg.hint.auto': 'Auto: Coins de l\'image.',
            'factory.bg.hint.picking': 'Cliquez sur le fond (moy. 5x5), ou Esc.',
            'factory.bg.hint.manual': 'Manuel: Défini.',
            'factory.frames': 'Cadres:',
            'factory.select_method': 'Méthode',
            'factory.select_desc': 'Taille: Filtre bruit; Ordre: Garde layout; Custom: Glisser-déposer.',
            'factory.method.size': 'Par Taille',
            'factory.method.order': 'Ordre Original',
            'factory.method.custom': 'Ordre Personnalisé',
            'factory.custom_hint': 'Glissez pour réorganiser, X pour supprimer.',
            'btn.add_to_library': 'Ajouter',
            'msg.added': 'Ajouté',
            'msg.upload_first': 'Chargez une image d\'abord',
            'msg.saved_png': 'Image sauvegardée',
            'msg.no_char': 'Sélectionnez un personnage',
            'msg.no_obj': 'Aucun objet détecté'
        },
        'de': {
            meta: {
                description: 'Pixel Sprite Studio ist ein leistungsstarkes Online-Tool zum Erstellen von Pixel-Art-Sprites. Hintergrund entfernen, Charaktere zusammenstellen, Animationen anpassen und als PNG oder GIF exportieren.',
                keywords: 'pixel art, sprite maker, sprite sheet, hintergrund entferner, game assets, gif generator'
            },
            'app.title': 'Pixel Sprite Studio - Sprite-Editor',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': 'Einstellungen',
            'ui.library': 'Bibliothek',
            'ui.add': 'Neu',
            'ui.tab.character': 'Charakter',
            'ui.tab.accessory': 'Zubehör',
            'ui.preview.title': 'Vorschau',
            'ui.preview.desc': 'Ergebnis',
            'ui.editor.title': 'Editor',
            'ui.editor.desc': 'Position & Größe',
            'ui.controls.title': 'Anpassung',
            'ui.msg.no_selection': 'Zubehör auswählen',
            'ctrl.bobbing': 'Hüpfen (Bobbing)',
            'ctrl.scale': 'Skalierung',
            'ctrl.rotation': 'Drehung',
            'ctrl.zoom': 'Ansicht Zoom',
            'ctrl.bgcolor': 'Hintergrundfarbe',
            'ctrl.transparent': 'Transparent',
            'ctrl.bg_desc': 'Beeinflusst Vorschau und Export.',
            'btn.save_png': 'PNG Export',
            'btn.save_gif': 'GIF Export',
            'tutorial.title': 'Schnellstart',
            'tutorial.subtitle': 'Erstelle dein Sprite in 3 Schritten!',
            'step.1.title': '1. Erstellen (Upload)',
            'step.1.desc': 'Öffne "Sprite-Fabrik", lade Bild hoch. Toleranz anpassen für automatische Freistellung!',
            'step.2.title': '2. Ausrüsten (Equip)',
            'step.2.desc': 'Wähle Charakter und Zubehör. Klicke zum Ausrüsten und Kombinieren!',
            'step.3.title': '3. Bearbeiten (Edit)',
            'step.3.desc': 'Nutze den Editor für Feinabstimmung. Klicke Export zum Speichern!',
            'factory.title': 'Sprite-Fabrik',
            'factory.tab.char': 'Charakter',
            'factory.tab.acc': 'Zubehör',
            'factory.source': 'Quelle',
            'factory.preview.placeholder': 'Bitte Bild hochladen',
            'factory.tolerance': 'Toleranz:',
            'factory.bg.status': 'Hintergrund',
            'factory.bg.auto': 'Auto',
            'factory.bg.manual': 'Manuell',
            'factory.bg.picking': 'Wählen',
            'factory.bg.pick_btn': 'Farbe wählen',
            'factory.bg.cancel_prod': 'Abbrechen',
            'factory.bg.reset_btn': 'Reset Auto',
            'factory.bg.hint.auto': 'Auto: Farbe aus Ecken.',
            'factory.bg.hint.picking': 'Klicke auf Hintergrund (5x5 Durschnitt), oder Esc.',
            'factory.bg.hint.manual': 'Manuell: Gewählt.',
            'factory.frames': 'Frames:',
            'factory.select_method': 'Methode',
            'factory.select_desc': 'Größe: Filtert Rauschen; Reihenfolge: Behält Layout; Custom: Drag & Drop.',
            'factory.method.size': 'Nach Größe',
            'factory.method.order': 'Original Reihenfolge',
            'factory.method.custom': 'Benutzerdefiniert',
            'factory.custom_hint': 'Ziehen zum Sortieren, X zum Löschen.',
            'btn.add_to_library': 'Hinzufügen',
            'msg.added': 'Hinzugefügt',
            'msg.upload_first': 'Bitte erst Bild hochladen',
            'msg.saved_png': 'Gespeichert',
            'msg.no_char': 'Erst Charakter wählen',
            'msg.no_obj': 'Kein Objekt gefunden'
        },
        'es': {
            meta: {
                description: 'Pixel Sprite Studio es una potente herramienta en línea para crear sprites de pixel art. Elimina fondos, ensambla personajes, ajusta animaciones y exporta como PNG o GIF.',
                keywords: 'pixel art, creador de sprites, hoja de sprites, eliminador de fondo, recursos de juego, generador gif'
            },
            'app.title': 'Pixel Sprite Studio - Creador de Sprites',
            'ui.brand': 'Pixel Sprite Studio',
            'ui.settings': 'Ajustes',
            'ui.library': 'Biblioteca',
            'ui.add': 'Añadir',
            'ui.tab.character': 'Personaje',
            'ui.tab.accessory': 'Accesorio',
            'ui.preview.title': 'Vista Previa',
            'ui.preview.desc': 'Resultado Final',
            'ui.editor.title': 'Editor',
            'ui.editor.desc': 'Posición y Tamaño',
            'ui.controls.title': 'Ajustes',
            'ui.msg.no_selection': 'Selecciona accesorio',
            'ctrl.bobbing': 'Rebote (Bobbing)',
            'ctrl.scale': 'Escala',
            'ctrl.rotation': 'Rotación',
            'ctrl.zoom': 'Zoom Vista',
            'ctrl.bgcolor': 'Color Fondo',
            'ctrl.transparent': 'Transparente',
            'ctrl.bg_desc': 'Afecta vista previa y exportación.',
            'btn.save_png': 'Exportar PNG',
            'btn.save_gif': 'Exportar GIF',
            'tutorial.title': 'Guía Rápida',
            'tutorial.subtitle': '¡Crea tu sprite en 3 pasos!',
            'step.1.title': '1. Generar (Upload)',
            'step.1.desc': 'Abre "Fábrica de Sprites", sube imagen. ¡Ajusta tolerancia para quitar fondo automáticamente!',
            'step.2.title': '2. Equipar (Equip)',
            'step.2.desc': 'Elige personaje y accesorios. ¡Clic para equipar y combinar libremente!',
            'step.3.title': '3. Editar (Edit)',
            'step.3.desc': 'Usa el editor para ajustar. ¡Clic en exportar para guardar tu obra!',
            'factory.title': 'Fábrica Sprites',
            'factory.tab.char': 'Personaje',
            'factory.tab.acc': 'Accesorio',
            'factory.source': 'Fuente',
            'factory.preview.placeholder': 'Sube una imagen',
            'factory.tolerance': 'Tolerancia:',
            'factory.bg.status': 'Color Fondo',
            'factory.bg.auto': 'Auto',
            'factory.bg.manual': 'Manual',
            'factory.bg.picking': 'Seleccionando',
            'factory.bg.pick_btn': 'Tomar Color',
            'factory.bg.cancel_prod': 'Cancelar',
            'factory.bg.reset_btn': 'Reset Auto',
            'factory.bg.hint.auto': 'Auto: Color de esquinas.',
            'factory.bg.hint.picking': 'Clic en fondo (promedio 5x5), o Esc.',
            'factory.bg.hint.manual': 'Manual: Sobrescrito.',
            'factory.frames': 'Fotogramas:',
            'factory.select_method': 'Método',
            'factory.select_desc': 'Tamaño: Filtra ruido; Orden: Mantiene diseño; Personal: Arrastrar.',
            'factory.method.size': 'Por Tamaño',
            'factory.method.order': 'Orden Original',
            'factory.method.custom': 'Orden Personalizado',
            'factory.custom_hint': 'Arrastra para ordenar, X para borrar.',
            'btn.add_to_library': 'Añadir',
            'msg.added': 'Añadido',
            'msg.upload_first': 'Sube imagen primero',
            'msg.saved_png': 'Guardado',
            'msg.no_char': 'Elige personaje primero',
            'msg.no_obj': 'No se detectaron objetos'
        }
    },

    init() {
        // Detect language: LocalStorage -> Navigator -> Default
        const stored = localStorage.getItem('pss_lang');
        const nav = navigator.language || navigator.userLanguage;

        if (stored && this.translations[stored]) {
            this.current = stored;
        } else if (nav) {
            // Try to match partial (e.g., 'ja-JP' -> 'ja')
            const code = nav.split('-')[0];
            if (this.translations[code]) {
                this.current = code;
            } else if (code === 'en') {
                this.current = 'en';
            } else {
                this.current = 'zh-TW';
            }
        } else {
            this.current = 'zh-TW';
        }

        this.updatePage();
        this.updateSelectElement();
    },

    setLanguage(lang) {
        if (this.translations[lang]) {
            this.current = lang;
            localStorage.setItem('pss_lang', lang);
            this.updatePage();
            return true;
        }
        return false;
    },

    get(key) {
        return this.translations[this.current][key] || key;
    },

    updatePage() {
        // Update elements with data-i18n
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.dataset.i18n;
            if (this.translations[this.current][key]) {
                // If it's an input button or submit, update value, else innerText
                if (el.tagName === 'INPUT' && (el.type === 'button' || el.type === 'submit')) {
                    el.value = this.translations[this.current][key];
                } else {
                    el.innerText = this.translations[this.current][key];
                }
            }
        });

        // Update document title
        if (this.translations[this.current]['app.title']) {
            document.title = this.translations[this.current]['app.title'];
        }

        // Update SEO Meta Tags
        const meta = this.translations[this.current].meta;
        if (meta) {
            this.setMeta('description', meta.description);
            this.setMeta('keywords', meta.keywords);
            this.setMetaProp('og:description', meta.description);
            this.setMetaProp('twitter:description', meta.description);
        }

        // Trigger custom event for other components
        window.dispatchEvent(new CustomEvent('lang-changed', { detail: { lang: this.current } }));
    },

    setMeta(name, content) {
        let el = document.querySelector(`meta[name="${name}"]`);
        if (!el) {
            el = document.createElement('meta');
            el.name = name;
            document.head.appendChild(el);
        }
        el.content = content;
    },

    setMetaProp(prop, content) {
        // For OG and Twitter tags
        let el = document.querySelector(`meta[property="${prop}"]`);
        if (!el) {
            el = document.createElement('meta');
            el.setAttribute('property', prop);
            document.head.appendChild(el);
        }
        el.content = content;
    },

    updateSelectElement() {
        const sel = document.getElementById('lang-select');
        if (sel) sel.value = this.current;
    }
};

// Auto-init when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    Lang.init();
    const sel = document.getElementById('lang-select');
    if (sel) {
        sel.addEventListener('change', (e) => {
            Lang.setLanguage(e.target.value);
        });
    }
});
